name: build

on:
    push:
        branches: [develop, main]

jobs:
    # Ubuntu-22 GCC
    build-ubuntu22-gcc12:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-12
                  CXX: g++-12
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu22-gcc11:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-11
                  CXX: g++-11
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu22-gcc10:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-10
                  CXX: g++-10
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu22-gcc9:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-9
                  CXX: g++-9
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests

    # Ubuntu-22 Clang
    build-ubuntu22-clang14:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang-14
                  CXX: clang++-14
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu22-clang13:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang-13
                  CXX: clang++-13
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu22-clang12:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang-12
                  CXX: clang++-12
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests

    # Ubuntu-20 GCC
    build-ubuntu20-gcc10:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-10
                  CXX: g++-10
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu20-gcc9:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-9
                  CXX: g++-9
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests

    # Ubuntu-20 Clang
    build-ubuntu20-clang12:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang-12
                  CXX: clang++-12
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu20-clang11:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang-11
                  CXX: clang++-11
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-ubuntu20-clang10:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang-10
                  CXX: clang++-10
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests

    # MacOS-12 Clang
    build-MacOS12-clang14:
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: clang
                  CXX: clang++
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests

    # MacOS-12 GCC
    build-MacOS12-gcc12:
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-12
                  CXX: g++-12
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
    build-MacOS12-gcc11:
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - env:
                  CC: gcc-11
                  CXX: g++-11
              run: |
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Debug -DTERMOX_BUILD_TESTS=ON -DTERMOX_BUILD_DEMOS=ON
                  make termox.all
                  ./tests/termox.unit.tests
