name: build

on:
  push:
    branches: [ develop, main ]

jobs:
  gcc-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - run: |
          mkdir build && cd build
          cmake .. && make -j2 demos
  clang-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - run: |
          mkdir build && cd build
          export CXX=clang++ && export CC=clang
          cmake .. && make -j2 demos
