name: build

# TODO Add sanitizers via cmake parameters.

on:
  push:
    branches: [ develop, main ]

jobs:
  # Ubuntu-20 GCC
  build-ubuntu20-gcc11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-11
          CXX: g++-11
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-ubuntu20-gcc10:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-ubuntu20-gcc9:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests

  # Ubuntu-20 Clang
  build-ubuntu20-clang12:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-12
          CXX: clang++-12
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-ubuntu20-clang11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-11
          CXX: clang++-11
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-ubuntu20-clang10:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-10
          CXX: clang++-10
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests

  # Ubuntu-18 GCC
  build-ubuntu18-gcc10:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-ubuntu18-gcc9:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests

  # Ubuntu-18 Clang
  build-ubuntu18-clang9:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-9
          CXX: clang++-9
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests

  # MacOS-10.15 Clang
  build-MacOS10-clang12:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang
          CXX: clang++
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests

  # MacOS-10.15 GCC
  build-MacOS10-gcc11:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-11
          CXX: g++-11
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-MacOS10-gcc10:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-MacOS10-gcc9:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
  build-MacOS10-gcc8:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-8
          CXX: g++-8
        run: |
          mkdir build && cd build
          cmake .. && make termox.all
          ./tests/termox.unit.tests
